### ISSUE TITLE
Organización 1era Reunión Venezuela.js

### ISSUE THREAD

**Issue by Villanuevand** [vzlajs/Venezuela.js#4]
Debemos organizarnos la primera reunión de Venezuela.js. Todos los miembros podrán opinar, teniendo en cuenta los siguientes puntos.
- **Día de la semana con mayor disponibilidad entre los participantes**.
- **Fecha**.
- **Canal. (Skype, Hangout, otros)**.

Los comentarios generados en este issue, deben ser contabilizados para proceder a la realización del evento. También serán recibidos comentarios y sugerencias. 

Esperamos contar con su participación.

**Comment by adrianObel** [comment]
Sábado ~9am por hangouts :D

**Comment by abr4xas** [comment]
Sábado, 1pm por hangouts... :) En las mañanas seria imposible para mi porque doy clases en fundacite carabobo

**Comment by Villanuevand** [comment]
Sábado de 9 - 12 / 3 - 6 y definitivamente por Hangout.

**Comment by ajsb85** [comment]
Si es por Skype tengo cuenta Premium y los invito a todos.
Este sabado voy a estar en el Agil Weekend 2015
http://comunidadagilven.wix.com/awve15
Así que mejor el próximo sabado u otro cualquier día
@Villanuevand si quieres haces un doodle.

**Comment by Villanuevand** [comment]
Se ha creado un [Doodle](http://doodle.com/), para elegir la fecha de la primera reunión de Venezuela.js. Las fechas tentativas son días sábados, esto por la disponibilidad de los miembros y para fomentar la participación. 

Pueden conseguir la encuesta en el siguiente [enlace](http://doodle.com/gnxngpgyeks554ue). 
_Todos los comentarios y recomendaciones son bienvenidos_.

**Comment by Villanuevand** [comment]
#### Hola muy buenos días javascripters!

La encuesta realizada en [Doodle](http://doodle.com/gnxngpgyeks554ue) indica que este próximo Sábado 20 de Junio, estaremos haciendo el primer Hangout de la comunidad.

Entre hoy y mañana estaremos colocando la duración del mimo y los posibles temas a conversar.
Esperamos contar con la participación de todos.

Saludos!

**Comment by abr4xas** [comment]
Claro que si :D

**Comment by ajsb85** [comment]
Cuenten conmigo :smiley:

**Comment by Villanuevand** [comment]
##### Buen día Javascripters!

La encuesta para elegir nuestra primera reunión ha sido cerrada, siendo el próximo sábado 20 de Junio la fecha seleccionada el evento. 
Tuvimos un total **4 votos**  que fueron **decisivos** para la elección. :laughing:

El evento comenzará a las 9:30 AM, será transmitido a traves de Google Hangout, tendrá una duración máxima de 1 hora 30 min, pudiendo finalizar antes de lo estipulado si los participantes en mutuo acuerdo así lo deciden.

Esta primera reunión tiene la intención de conocernos un poco, hablar sobre el lenguaje y definir cuales serán los próximos pasos de la comunidad. 

Esperemos que esta primera reunión sea agradable y fructifera para todos. 

**¡Nos vemos el sábado a las 9:30 AM.** :coffee:

**Comment by ajsb85** [comment]
Enlace del evento en G+ creado por @abr4xas 
https://plus.google.com/events/c672s0emdanaofcj3t8iboa9ld8/rsvp/COWftdzMrr2EoQE/ATTENDING?cfem=1

**Comment by ajsb85** [comment]
@Villanuevand @abr4xas hagan la invitación formal al grupo :smiley: 
https://groups.google.com/forum/?fromgroups#!forum/venezuelajs

**Comment by Villanuevand** [comment]
La reunión se efectuó a pesar de algunos impedimentos técnicos,
Muchas gracias a todos por sus asistencia.
